---
apiVersion: apps/v1
kind: RunnerDeployment
metadata:
  name: k8s-runners-deployment1
  namespace: actions
spec:
  template:
    spec:
      repository: jamcarbon/test-rust
      labels:
        - Auto-scalable runners 
      env: []