---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners-deployment1
spec:
  template:
    spec:
      repository: jamcarbon/test-rust
      labels:
        - Auto-scalable runners 
      env: []